# Generated by Django 4.0.6 on 2022-08-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_order_order_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
